# Generated by Django 5.2.3 on 2025-06-24 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_caste_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtendedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('urban_rural', models.CharField(blank=True, max_length=10)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('disability', models.CharField(blank=True, max_length=10)),
                ('ex_serviceman', models.CharField(blank=True, max_length=10)),
                ('priority_ex_service', models.CharField(blank=True, max_length=10)),
                ('eyesight', models.CharField(blank=True, max_length=20)),
                ('chest', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
