# Generated by Django 5.2 on 2025-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userextendedprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='location',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='income_range',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='target_gender',
        ),
        migrations.AddField(
            model_name='scheme',
            name='apply_link',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=10),
        ),
        migrations.AddField(
            model_name='scheme',
            name='income_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_age',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheme',
            name='title',
            field=models.CharField(default='Untitled Scheme', max_length=255),
            preserve_default=False,
        ),
    ]
