# Generated by Django 5.2 on 2025-06-27 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_location_scheme_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='state',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='income_limit',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='title',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='income_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='target_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UserCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
