# Generated by Django 5.2 on 2025-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_exam_description_exam_link_alter_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='link',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
