# Generated by Django 5.2 on 2025-08-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_exam_description_remove_exam_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD')], max_length=50)),
                ('income', models.CharField(blank=True, choices=[('<1 Lakh', '<1 Lakh'), ('1-3 Lakhs', '1-3 Lakhs'), ('3-5 Lakhs', '3-5 Lakhs'), ('5-10 Lakhs', '5-10 Lakhs'), ('>10 Lakhs', '>10 Lakhs')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('interests', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
