# Generated by Django 5.0.8 on 2025-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(default='Government', max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(default='Government', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
