# Generated by Django 5.2 on 2025-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_exam_eligibility_exam_location_exam_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='location',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='type',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='location',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(default='Government', max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(default='Central', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
