# Generated by Django 5.2 on 2025-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_exam_eligibility_remove_exam_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(default='Online', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(default='Government', max_length=100),
        ),
    ]
