# Generated by Django 5.2 on 2025-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_date_scheme_end_date_exam_location_exam_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(default='Offline', max_length=50),
        ),
    ]
