# Generated by Django 5.2 on 2025-08-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rename_date_exam_end_date_remove_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('State Level', 'State Level'), ('National Level', 'National Level')], default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('All India', 'All India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], default='Offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Health', 'Health'), ('Finance', 'Finance'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Welfare', 'Welfare'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan')], default='Central Government', max_length=50),
        ),
    ]
