# Generated by Django 5.2 on 2025-08-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_exam_exam_type_alter_exam_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('All India', 'All India')], default='All India', max_length=100),
        ),
    ]
