# Generated by Django 5.2 on 2025-08-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_exam_category_alter_exam_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('All India', 'All India')], default='All India', max_length=100),
        ),
    ]
