# Generated by Django 5.2.4 on 2025-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_alter_exam_location_alter_scheme_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='location',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Health', 'Health'), ('Finance', 'Finance'), ('General', 'General'), ('Entrepreneurship', 'Entrepreneurship'), ('Housing', 'Housing'), ('Welfare', 'Welfare'), ('Insurance', 'Insurance'), ('Pension', 'Pension'), ('Food Corporation', 'Food Corporation'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management'), ('Science', 'Science'), ('Design', 'Design'), ('Employment', 'Employment'), ('Insurance', 'Insurance'), ('Food Corporation', 'Food Corporation'), ('Agriculture', 'Agriculture'), ('Hotel Management', 'Hotel Management')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('18+ years', '18+ years'), ('18-50 years', '18-50 years'), ('18-70 years', '18-70 years'), ('18-40 years', '18-40 years'), ('Senior Citizens', 'Senior Citizens'), ('BPL Families', 'BPL Families'), ('SC/ST/Women', 'SC/ST/Women'), ('Rural Population', 'Rural Population'), ('Farmers', 'Farmers'), ('State Residents', 'State Residents'), ('Girl Students', 'Girl Students'), ('Girls from BPL families', 'Girls from BPL families'), ('Graduate, Unemployed', 'Graduate, Unemployed'), ('All Residents', 'All Residents'), ('Startups registered in Delhi', 'Startups registered in Delhi'), ('Low Income', 'Low Income')], max_length=100, null=True),
        ),
    ]
