# Generated by Django 5.2 on 2025-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_exam_category_exam_location_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('All India', 'All India'), ('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Maharastra', 'Maharastra'), ('West Bengal', 'West Bengal'), ('Kerala', 'Kerala'), ('Rural India', 'Rural India'), ('Mumbai', 'Mumbai')], default='All India', max_length=100),
        ),
    ]
