# Generated by Django 5.2 on 2025-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_alter_exam_category_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management'), ('Science', 'Science'), ('Design', 'Design'), ('Employment', 'Employment'), ('Insurance', 'Insurance'), ('Food Corporation', 'Food Corporation'), ('Agriculture', 'Agriculture'), ('Hotel Management', 'Hotel Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('University Level', 'University Level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Welfare', 'Welfare'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan'), ('Employment', 'Employment'), ('Training', 'Training'), ('Pension', 'Pension'), ('Insurance', 'Insurance'), ('Financial Assistance', 'Financial Assistance'), ('Subsidy', 'Subsidy'), ('Allowance', 'Allowance')], max_length=50),
        ),
    ]
