# Generated by Django 5.2 on 2025-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_alter_exam_category_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='eligibility',
            new_name='s_eligibility',
        ),
        migrations.AddField(
            model_name='exam',
            name='e_eligibility',
            field=models.CharField(choices=[('10th_pass', '10th Pass'), ('12th_pass', '12th Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], default='Graduate', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management'), ('Science', 'Science'), ('Design', 'Design'), ('Employment', 'Employment'), ('Insurance', 'Insurance'), ('Food Corporation', 'Food Corporation'), ('Agriculture', 'Agriculture'), ('Hotel Management', 'Hotel Management'), ('Environment', 'Environment')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('University Level', 'University Level'), ('Professional', 'Professional')], default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India'), ('Coastal Cities', 'Coastal Cities')], default='All India', max_length=100),
        ),
    ]
