# Generated by Django 5.2 on 2025-08-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_alter_exam_category_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
