from django.core.management.base import BaseCommand
from my_app.models import Exam, Scheme
from datetime import date, timedelta


class Command(BaseCommand):
    help = "Seed the database with initial Exam and Scheme data"

    def handle(self, *args, **kwargs):
        # -------- Exams --------
        from datetime import date

        exams = [
                {
                    "name": "JEE Main",
                    "exam_type": "Government",
                    "category": "Engineering",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 1, 6),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1000 (General), ₹500 (Reserved). Duration: 3 hours. Conducted by NTA. Two papers: Paper 1 for B.E./B.Tech, Paper 2 for B.Arch/B.Planning.",
                },
                {
                    "name": "NEET",
                    "exam_type": "Government",
                    "category": "Medical",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 5, 7),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1600 (General), ₹1500 (OBC), ₹900 (SC/ST). 180 multiple-choice questions. Duration: 3 hours 20 minutes. Qualifying exam for MBBS, BDS, AYUSH courses.",
                },
                {
                    "name": "UPSC Civil Services",
                    "exam_type": "Government",
                    "category": "Civil Services",
                    "location": "Delhi",
                    "mode": "Offline",
                    "date": date(2025, 5, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Three-stage exam: Prelims, Mains, Interview. Application fee: ₹100. Age limit: 21-32 years (relaxation for reserved categories). One of the toughest exams in India.",
                },
                {
                    "name": "CAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 11, 24),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹2400 (General), ₹1200 (Reserved). Duration: 2 hours. 100 questions. Accepts scores: IIMs, FMS, MDI, SPJIMR and other top B-schools. Percentile-based scoring.",
                },
                {
                    "name": "GATE",
                    "exam_type": "National Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 2, 8),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1800 (General), ₹900 (Reserved). Duration: 3 hours. Score valid for 3 years. Used for PG admissions in IITs, NITs, IIITs and PSU recruitments.",
                },
                {
                    "name": "CLAT",
                    "exam_type": "National Level",
                    "category": "Law",
                    "location": "Hyderabad",
                    "mode": "Offline",
                    "date": date(2025, 12, 8),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹4000 (General), ₹3500 (Reserved). Duration: 2 hours. 150 multiple-choice questions. Accepting colleges: NLUs, other law universities. Sections: English, GK, Legal Reasoning, Logical Reasoning, Quantitative Techniques.",
                },
                {
                    "name": "SSC CGL",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 7, 14),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹100 (General), no fee (Women/SC/ST/PWD). Four tiers: Tier I (Online), Tier II (Online), Tier III (Descriptive), Tier IV (Skill Test). Age limit: 18-32 years. Recruits for various government departments.",
                },
                {
                    "name": "IBPS PO",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "West Bengal",
                    "mode": "Online",
                    "date": date(2025, 9, 20),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹850 (General), ₹175 (Reserved). Three phases: Prelims, Mains, Interview. Age limit: 20-30 years. Probationary Officer post in public sector banks. Basic pay scale: ₹36,000-₹63,840.",
                },
                {
                    "name": "NDA",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "Delhi",
                    "mode": "Offline",
                    "date": date(2025, 4, 14),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹100. Conducted twice a year. Two sections: Mathematics and General Ability. SSB interview for final selection. Training at Indian Military Academy, Naval Academy, Air Force Academy.",
                },
                {
                    "name": "NET",
                    "exam_type": "Government",
                    "category": "Teaching",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 12, 5),
                    "e_eligibility": "Post Graduate",
                    "additional_info": "Application fee: ₹1100 (General), ₹550 (OBC), ₹275 (SC/ST/PWD). Eligibility for Assistant Professor and Junior Research Fellowship. Two papers: Paper I (Teaching aptitude), Paper II (Subject specific).",
                },
                {
                    "name": "AIIMS MBBS",
                    "exam_type": "Government",
                    "category": "Medical",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 20),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1500 (General), ₹1200 (OBC), ₹800 (SC/ST). 200 multiple-choice questions. Duration: 3.5 hours. Minimum 60% aggregate in PCB for eligibility. Highly competitive with less than 1% selection rate.",
                },
                {
                    "name": "IIT JAM",
                    "exam_type": "National Level",
                    "category": "Science",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 2, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1500 (General), ₹750 (Female/Reserved). Duration: 3 hours. For admission to MSc and other PG courses at IITs. Seven test papers: Biotechnology, Chemistry, Economics, etc.",
                },
                {
                    "name": "NIFT",
                    "exam_type": "National Level",
                    "category": "Design",
                    "location": "Maharashtra",
                    "mode": "Offline",
                    "date": date(2025, 2, 18),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹2000 (General), ₹1500 (Reserved). Two parts: Creative Ability Test (CAT) and General Ability Test (GAT). For admission to Bachelor and Master programs in Design. Campuses in Delhi, Mumbai, Kolkata, Bengaluru, etc.",
                },
                {
                    "name": "NID",
                    "exam_type": "National Level",
                    "category": "Design",
                    "location": "Ahmedabad",
                    "mode": "Offline",
                    "date": date(2025, 1, 8),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹2000 (General), ₹1500 (Reserved). Two-stage selection process: Design Aptitude Test (DAT) Prelims and Mains. For admission to Bachelor of Design (B.Des) and Master of Design (M.Des).",
                },
                {
                    "name": "IIFT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2024, 11, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹2000 (General), ₹1000 (Reserved). Duration: 2 hours. For MBA in International Business. 110 multiple-choice questions. Sections: Verbal Ability, Reading Comprehension, DI, Logical Reasoning, GK.",
                },
                {
                    "name": "XAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 1, 3),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹2000. Duration: 3 hours. 100 questions plus essay. Accepted by XLRI and 150+ other B-schools. Sections: Verbal Ability, Decision Making, Quantitative Ability, GK.",
                },
                {
                    "name": "MAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 2, 12),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1650. Conducted 4 times a year. Duration: 2.5 hours. 200 questions. Accepted by 600+ B-schools. Can be taken in both online and offline mode.",
                },
                {
                    "name": "SSC CHSL",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 12),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (Women/SC/ST/PWD). Three tiers: Tier I (Online), Tier II (Descriptive), Tier III (Skill Test). Posts: LDC, JSA, PA, SA, DEO. Age limit: 18-27 years.",
                },
                {
                    "name": "SSC JE",
                    "exam_type": "Government",
                    "category": "Engineering",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 1),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹100 (General), no fee (Women/SC/ST/PWD). Two papers: Paper I (Objective), Paper II (Descriptive). For Junior Engineer posts in Civil, Mechanical, Electrical, Quantity Surveying branches.",
                },
                {
                    "name": "SSC GD",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 5),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (Women/SC/ST/PWD). For Constable posts in CAPFs, NIA, SSF and Rifleman in Assam Rifles. Physical Efficiency Test (PET) and Medical Test after written exam.",
                },
                {
                    "name": "RBI Grade B",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹850 (General), ₹100 (SC/ST/PWD). Three phases: Prelims, Mains, Interview. Age limit: 21-30 years. One of the most prestigious banking exams. Starting basic pay: ₹55,200.",
                },
                {
                    "name": "SBI PO",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 12),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750 (General), ₹125 (SC/ST/PWD). Three phases: Prelims, Mains, Interview + Group Exercise. Starting basic pay: ₹41,960. Four-month probation period with stipend.",
                },
                {
                    "name": "SBI Clerk",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750 (General), ₹125 (SC/ST/PWD). Two phases: Prelims and Mains. Starting basic pay: ₹26,000. Job profile includes cash management, customer service, and back-office operations.",
                },
                {
                    "name": "IBPS Clerk",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 10, 30),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹850 (General), ₹175 (SC/ST/PWD). Two tiers: Prelims and Mains. Starting basic pay: ₹26,000. Posting primarily in rural and semi-urban areas. Language proficiency test in local language required.",
                },
                {
                    "name": "IBPS RRB",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹850 (General), ₹175 (SC/ST/PWD). For Officer Scale I, II, III and Office Assistant posts in Regional Rural Banks. Language proficiency test in local language required for Office Assistant post.",
                },
                {
                    "name": "LIC AAO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 5),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹700 (General), ₹85 (SC/ST/PWD). Three phases: Prelims, Mains, Interview. Starting basic pay: ₹53,600. Specializations: Generalist, IT, Chartered Accountant, Actuarial, Rajbhasha.",
                },
                {
                    "name": "LIC ADO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 1),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹700 (General), ₹85 (SC/ST/PWD). For Apprentice Development Officer posts. Two phases: Prelims and Mains. Starting basic pay: ₹33,000. Focus on recruitment and training of agents.",
                },
                {
                    "name": "NICL AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 25),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750 (General), ₹100 (SC/ST/PWD). For Administrative Officer posts. Three phases: Prelims, Mains, Interview. Starting basic pay: ₹50,925. Specializations: Generalist, Accounts, Legal, IT, Engineering.",
                },
                {
                    "name": "UIIC AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750 (General), ₹100 (SC/ST/PWD). For Administrative Officer posts. Three phases: Prelims, Mains, Interview. Starting basic pay: ₹50,000. Specializations: Generalist, Legal, IT, Accounts, Automobile Engineering.",
                },
                {
                    "name": "NIACL AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 1),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750 (General), ₹100 (SC/ST/PWD). For Administrative Officer posts. Three phases: Prelims, Mains, Interview. Starting basic pay: ₹50,000. Specializations: Generalist, Accounts, Legal, IT, Engineering.",
                },
                {
                    "name": "FCI",
                    "exam_type": "Government",
                    "category": "Food Corporation",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 30),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹500 (General), ₹350 (OBC), ₹150 (SC/ST/PWD). For Manager, Assistant Grade, Junior Engineer, Typist posts. Two phases: Online Test and Interview. Good career growth opportunities.",
                },
                {
                    "name": "CISF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 28),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (SC/ST). For Constable/General Duty posts. Physical Efficiency Test and Medical Test after written exam. Provides security to critical infrastructure installations.",
                },
                {
                    "name": "CRPF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 5),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (SC/ST). For Constable/General Duty posts. Largest paramilitary force in India. Physical Efficiency Test and Medical Test after written exam. Deployed in internal security duties.",
                },
                {
                    "name": "BSF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 10),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (SC/ST). For Constable/General Duty posts. Primary border guarding force of India. Physical Efficiency Test and Medical Test after written exam. Deployed on international borders.",
                },
                {
                    "name": "ITBP",
                    "exam_type": "Private",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 15),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹100 (General), no fee (SC/ST). For Constable/General Duty posts. Specialized in mountain warfare. Deployed primarily on Indo-China border. Physical Efficiency Test and Medical Test after written exam.",
                },
                {
                    "name": "CDS",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 2, 15),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹200. Conducted twice a year. For admission to Indian Military Academy, Indian Naval Academy, Air Force Academy, and Officers Training Academy. SSB interview after written exam. Duration: 5 years service mandatory.",
                },
                {
                    "name": "AFCAT",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 20),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹250. Conducted twice a year. For Flying Branch and Ground Duty (Technical and Non-Technical) branches in Indian Air Force. SSB interview after written exam. Starting salary: ₹56,100.",
                },
                {
                    "name": "INET",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 5),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹295. For Commissioned Officer posts in Indian Navy. Two branches: Executive and Education. SSB interview after written exam. Starting salary: ₹56,100. Good opportunities for career progression.",
                },
                {
                    "name": "ESIC SSO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹500 (General), ₹250 (SC/ST/PWD). For Social Security Officer posts. Two phases: Prelims and Mains. Starting basic pay: ₹44,900. Works under Ministry of Labour and Employment.",
                },
                {
                    "name": "EPFO SSA",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 10, 30),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹700 (General), no fee (SC/ST/PWD/Female). For Social Security Assistant posts. Two phases: Prelims and Mains. Starting basic pay: ₹29,200. Typing test required in English and Hindi.",
                },
                {
                    "name": "EPFO AO",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 12, 5),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹700 (General), no fee (SC/ST/PWD/Female). For Enforcement Officer/Accounts Officer posts. Two phases: Prelims and Mains. Starting basic pay: ₹44,900. Works under Ministry of Labour and Employment.",
                },
                {
                    "name": "NTA UGC NET",
                    "exam_type": "Government",
                    "category": "Teaching",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 15),
                    "e_eligibility": "Post Graduate",
                    "additional_info": "Application fee: ₹1100 (General), ₹550 (OBC), ₹275 (SC/ST/PWD). Two papers: Paper I (Teaching aptitude), Paper II (Subject specific). Eligibility for Assistant Professor and Junior Research Fellowship. Score valid for lifetime for Assistant Professor.",
                },
                {
                    "name": "CSIR UGC NET",
                    "exam_type": "Government",
                    "category": "Science",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 5),
                    "e_eligibility": "Post Graduate",
                    "additional_info": "Application fee: ₹1100 (General), ₹550 (OBC), ₹275 (SC/ST/PWD). For Junior Research Fellowship and Lectureship in Science subjects. Five subjects: Chemical Sciences, Earth Sciences, Life Sciences, Mathematical Sciences, Physical Sciences.",
                },
                {
                    "name": "ICAR AIEEA",
                    "exam_type": "Government",
                    "category": "Agriculture",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 20),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹750 (General), ₹375 (OBC), ₹275 (SC/ST/PWD). For admission to BSc Agriculture and other UG courses in agriculture universities. 180 multiple-choice questions. Duration: 2.5 hours.",
                },
                {
                    "name": "NCHMCT JEE",
                    "exam_type": "National Level",
                    "category": "Hotel Management",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 25),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹900 (General), ₹450 (SC/ST). For admission to BSc Hospitality and Hotel Administration. 200 questions from Numerical Ability, Reasoning, English, Aptitude for Service Sector, General Knowledge. Duration: 3 hours.",
                },
                {
                    "name": "IIIT Hyderabad Entrance",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Hyderabad",
                    "mode": "Online",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹2000. For admission to B.Tech programs. Based on JEE Main score or UGEE (Undergraduate Entrance Examination). Known for strong focus on computer science and research.",
                },
                {
                    "name": "BITSAT",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 6, 15),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹3400 (Male), ₹2900 (Female). For admission to BITS Pilani, Goa, Hyderabad campuses. 150 questions from Physics, Chemistry, English, Logical Reasoning, Mathematics/Biology. Duration: 3 hours.",
                },
                {
                    "name": "VITEEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1150. For admission to VIT campuses. 125 questions from Physics, Chemistry, Mathematics/Biology, English, Aptitude. Duration: 2.5 hours. One of the largest engineering entrance exams in India.",
                },
                {
                    "name": "SRMJEEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 5, 1),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1200. For admission to SRM Institute of Science and Technology. 125 questions from Physics, Chemistry, Mathematics/Biology. Duration: 2.5 hours. Campuses in Chennai, Amaravati, Sonipat.",
                },
                {
                    "name": "KIITEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Odisha",
                    "mode": "Online",
                    "date": date(2025, 4, 5),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1500. For admission to KIIT University. 120 questions from Physics, Chemistry, Mathematics. Duration: 3 hours. Also offers courses in Law, Management, Architecture, etc.",
                },
                {
                    "name": "COMEDK",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1500. For admission to engineering colleges in Karnataka. 180 questions from Physics, Chemistry, Mathematics. Duration: 3 hours. Accepting colleges: 190+ engineering colleges.",
                },
                {
                    "name": "KCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Offline",
                    "date": date(2025, 4, 15),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹500 (General), ₹250 (SC/ST). For admission to professional courses in Karnataka. 180 questions from Physics, Chemistry, Mathematics/Biology. Duration: 1.5 hours per subject. Government seat quota available.",
                },
                {
                    "name": "MHT CET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 5, 1),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹800 (General), ₹600 (Reserved). For admission to engineering and pharmacy colleges in Maharashtra. 150 questions from Physics, Chemistry, Mathematics. Duration: 3 hours. 80% weightage to CET score, 20% to 12th marks.",
                },
                {
                    "name": "TS EAMCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Telangana",
                    "mode": "Online",
                    "date": date(2025, 5, 5),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹800 (General), ₹400 (SC/ST). For admission to professional courses in Telangana. 160 questions from Physics, Chemistry, Mathematics. Duration: 3 hours. 75% weightage to EAMCET score, 25% to 12th marks.",
                },
                {
                    "name": "AP EAMCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Andhra Pradesh",
                    "mode": "Online",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹800 (General), ₹400 (SC/ST). For admission to professional courses in Andhra Pradesh. 160 questions from Physics, Chemistry, Mathematics. Duration: 3 hours. 75% weightage to EAMCET score, 25% to 12th marks.",
                },
                {
                    "name": "WBJEE",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "West Bengal",
                    "mode": "Offline",
                    "date": date(2025, 4, 25),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹500 (General), ₹400 (SC/ST). For admission to engineering and medical colleges in West Bengal. Two papers: Mathematics (100 questions) and Physics+Chemistry (100 questions). Duration: 2 hours each paper.",
                },
                {
                    "name": "OJEE",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Odisha",
                    "mode": "Online",
                    "date": date(2025, 5, 3),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹1000 (General), ₹500 (SC/ST). For admission to engineering, medical, MBA, MCA courses in Odisha. Multiple papers for different courses. Duration: 2 hours. Accepting colleges: 100+ colleges in Odisha.",
                },
                {
                    "name": "GUJCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Gujarat",
                    "mode": "Offline",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹300 (General), ₹250 (SC/ST). For admission to engineering and pharmacy colleges in Gujarat. 120 questions from Physics, Chemistry, Mathematics/Biology. Duration: 3 hours. 60% weightage to GUJCET, 40% to 12th marks.",
                },
                {
                    "name": "CGPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Chhattisgarh",
                    "mode": "Offline",
                    "date": date(2025, 6, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹400 (General), ₹300 (OBC), ₹200 (SC/ST). Three stages: Prelims, Mains, Interview. For State Civil Services, State Police Services, and other administrative posts. Age limit: 21-30 years.",
                },
                {
                    "name": "MPPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Madhya Pradesh",
                    "mode": "Offline",
                    "date": date(2025, 6, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹500 (General), ₹250 (OBC), ₹150 (SC/ST). Three stages: Prelims, Mains, Interview. For State Civil Services, State Police Services, and other administrative posts. Age limit: 21-40 years.",
                },
                {
                    "name": "TNPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 8, 1),
                    "e_eligibility": "Post Graduate",
                    "additional_info": "Application fee: ₹150 (General), no fee (SC/ST). For Group I, II, III, IV services in Tamil Nadu. Three stages for Group I: Prelims, Mains, Interview. Age limit varies by post. Special reservation for Tamil medium students.",
                },
                {
                    "name": "UKPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Uttarakhand",
                    "mode": "Online",
                    "date": date(2025, 8, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹200 (General), ₹100 (OBC), ₹60 (SC/ST). Three stages: Prelims, Mains, Interview. For State Civil Services, State Police Services, and other administrative posts. Age limit: 21-42 years.",
                },
                {
                    "name": "National Welfare Awareness Test",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 15),
                    "e_eligibility": "10th Pass",
                    "additional_info": "Application fee: ₹500. 100 multiple-choice questions on Welfareal science. Duration: 2 hours. Certificate provided to all participants. Merit-based scholarships for top performers. Conducted by Ministry of Welfare.",
                },
                {
                    "name": "Green Skills Certification Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 22),
                    "e_eligibility": "12th Pass",
                    "additional_info": "Application fee: ₹750. Focus on sustainable development practices. Two parts: Theory and Practical assessment. Duration: 3 hours. Certification valid for 3 years. Job opportunities in renewable energy sector.",
                },
                {
                    "name": "Climate Change National Level Certification",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Multiple Cities",
                    "mode": "Offline",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1200. Advanced certification for climate science professionals. Two papers: Climate Science and Policy, Mitigation and Adaptation Strategies. Duration: 3 hours each. Recognized by UNFCCC.",
                },
                {
                    "name": "Renewable Energy Engineer Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2025, 6, 5),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1500. For certification as Renewable Energy Engineer. Two parts: Technical Knowledge and Project Management. Duration: 4 hours. Recognized by Ministry of New and Renewable Energy. Valid for 5 years.",
                },
                {
                    "name": "Welfareal Impact Assessment Exam",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "Kerala",
                    "mode": "Online",
                    "date": date(2025, 7, 20),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1000. For EIA consultants and professionals. Based on EIA Notification 2006 and amendments. Duration: 3 hours. Certification mandatory for conducting EIAs. Recognized by MoEFCC.",
                },
                {
                    "name": "Wildlife Conservation Officer Exam",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 8, 12),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹800. For recruitment in Forest Department as Wildlife Conservation Officer. Physical test and interview after written exam. Field postings in national parks and wildlife sanctuaries. Starting salary: ₹45,000.",
                },
                {
                    "name": "Sustainable Development Certification",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 9, 8),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹900. Covers SDGs and implementation strategies. Case study based assessment. Duration: 3 hours. Recognized by NITI Aayog. Useful for CSR professionals and development sector workers.",
                },
                {
                    "name": "Forest Officer Recruitment Exam",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 10, 15),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1000. For Indian Forest Service (IFoS) and State Forest Services. Three stages: Prelims, Mains, Interview. Physical test and medical examination. Prestigious service with postings in forest areas across India.",
                },
                {
                    "name": "Water Resource Management Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 11, 5),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹850. Focus on integrated water resource management. Two parts: Theory and Case Studies. Duration: 3.5 hours. Certification recognized by Ministry of Water Resources. Valid for 4 years.",
                },
                {
                    "name": "Welfareal Science Olympiad",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Multiple Cities",
                    "mode": "Offline",
                    "date": date(2025, 12, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹600. For students and professionals in Welfareal science. Two levels: Junior (UG) and Senior (PG/Professionals). Duration: 3 hours. Cash prizes and research grants for winners. Conducted by Indian Welfareal Association.",
                },
                {
                    "name": "Pollution Control Board Exam",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 1, 25),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1000. For Junior Welfareal Engineer posts in SPCBs and CPCB. Two stages: Written exam and Interview. Starting salary: ₹50,000. Knowledge of Welfareal laws and standards required.",
                },
                {
                    "name": "Eco-Auditor Certification",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 2, 18),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1200. For Welfareal auditing professionals. Based on ISO 14001 standards. Two parts: Theory and Practical assessment. Duration: 4 hours. Certification recognized by QCI. Valid for 3 years.",
                },
                {
                    "name": "Biodiversity Conservation Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 22),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹800. On World Water Day. Focus on biodiversity laws and conservation practices. Duration: 3 hours. Certification recognized by National Biodiversity Authority. Useful for researchers and conservation practitioners.",
                },
                {
                    "name": "Climate Analyst Certification",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Hyderabad",
                    "mode": "Online",
                    "date": date(2025, 4, 30),
                    "e_eligibility": "Post Graduate",
                    "additional_info": "Application fee: ₹1500. Advanced certification for climate data analysis. Requires knowledge of statistical tools and climate models. Duration: 4 hours. Recognized by IMD and MoES. High demand in research institutions.",
                },
                {
                    "name": "Welfareal Law Entrance Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 5, 25),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1000. For admission to LLM in Welfareal Law. Based on Welfareal legislation and case laws. Duration: 3 hours. Accepting colleges: NLUs and other law universities. Growing field with good career prospects.",
                },
                {
                    "name": "Waste Management National Level Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2025, 6, 20),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹900. Focus on solid waste management rules and practices. Two parts: Theory and Case Studies. Duration: 3 hours. Certification recognized by CPCB. Valid for 4 years.",
                },
                {
                    "name": "Green Building Consultant Exam",
                    "exam_type": "Private",
                    "category": "Welfare",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 7, 15),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹2000. Based on IGBC and GRIHA rating systems. Two parts: Theory and Project Assessment. Duration: 4 hours. Certification recognized by IGBC. High demand in construction industry.",
                },
                {
                    "name": "Marine Conservation Officer Exam",
                    "exam_type": "Government",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 8, 28),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹750. For coastal and marine conservation posts. Physical fitness test and swimming test required. Duration: 3 hours. Postings in coastal states and union territories. Starting salary: ₹48,000.",
                },
                {
                    "name": "Welfareal Education Certification",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 20),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹800. For teachers and educators in Welfareal science. Focus on pedagogy and curriculum development. Duration: 3 hours. Certification recognized by NCERT. Valid for 5 years.",
                },
                {
                    "name": "Carbon Footprint Analyst Exam",
                    "exam_type": "National Level",
                    "category": "Welfare",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 10, 10),
                    "e_eligibility": "Graduate",
                    "additional_info": "Application fee: ₹1200. For carbon accounting and management professionals. Based on GHG Protocol and ISO 14064. Duration: 3.5 hours. Certification recognized by BEE. High demand in corporate sustainability roles.",
                }
            ]

        for exam_data in exams:
            exam, created = Exam.objects.update_or_create(
                name=exam_data["name"], defaults=exam_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Exam created: {exam.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Exam updated: {exam.name}"))

        # -------- Schemes --------
        schemes = [
            {
                "name": "Central Scholarship Scheme",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for meritorious students.",
                "s_eligibility": "12th Pass",
                "benefits": "Covers tuition fees and stipend.",
                "location": "All India",
                "date": date(2025, 4, 5),
                "additional_info": "Monthly stipend: ₹1000-₹2000 based on course. Application period: April-June. Renewal required each year with minimum 50% marks. Documents needed: Income certificate, marksheets, bank account details.",
            },
            {
                "name": "Startup India Loan",
                "category": "Entrepreneurship",
                "scheme_type": "Loan",
                "description": "Financial support for startups.",
                "s_eligibility": "Graduate",
                "benefits": "Low-interest loan up to 10 Lakhs.",
                "location": "Delhi",
                "date": date(2025, 1, 10),
                "additional_info": "Interest rate: 7-8% per annum. Moratorium period: 6 months. Repayment period: 5 years. Collateral-free for businesses registered within last 5 years. Mentorship program included.",
            },
            {
                "name": "Ayushman Bharat",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Healthcare scheme for low-income families.",
                "s_eligibility": "10th Pass",
                "benefits": "Free health coverage up to 5 Lakhs.",
                "location": "All India",
                "date": date(2025, 3, 15),
                "additional_info": "Covers secondary and tertiary hospitalization. Beneficiary family size: Up to 5 members. Cashless treatment at empaneled hospitals. Pre-existing diseases covered from day one. Golden card required for availing benefits.",
            },
            {
                "name": "PM Kisan Samman Nidhi",
                "category": "Employment",
                "scheme_type": "Central Government",
                "description": "Income support for farmers.",
                "s_eligibility": "10th Pass",
                "benefits": "6000 INR per year.",
                "location": "West Bengal",
                "date": date(2025, 2, 5),
                "additional_info": "Amount disbursed in 3 equal installments of ₹2000. Landholding criteria: Up to 2 hectares. Institutional landowners not eligible. Aadhaar linked bank account mandatory. Application through Common Service Centers or state agriculture department.",
            },
            {
                "name": "Skill India Mission",
                "category": "Employment",
                "scheme_type": "Training",
                "description": "Skill development for youth.",
                "s_eligibility": "12th Pass",
                "benefits": "Free training programs.",
                "location": "Maharashtra",
                "date": date(2025, 6, 5),
                "additional_info": "Over 40 sectors covered including construction, retail, automotive, etc. Training duration: 3-6 months. Placement assistance provided. Stipend of ₹5000 during training. Certification from National Skill Development Corporation.",
            },
            {
                "name": "Digital India Initiative",
                "category": "General",
                "scheme_type": "Central Government",
                "description": "Promoting digital infrastructure.",
                "s_eligibility": "Graduate",
                "benefits": "Support for digital adoption.",
                "location": "Karnataka",
                "date": date(2025, 1, 20),
                "additional_info": "Focus on digital literacy, digital infrastructure, and digital services. Components include BharatNet, Digital Locker, e-Hospital, e-Sign. Training programs for digital skills. Grants for digital startups.",
            },
            {
                "name": "National Pension Scheme",
                "category": "Finance",
                "scheme_type": "Central Government",
                "description": "Retirement savings scheme.",
                "s_eligibility": "Graduate",
                "benefits": "Tax benefits and pension.",
                "location": "All India",
                "date": date(2025, 1, 5),
                "additional_info": "Contribution: Minimum ₹500 per month. Retirement age: 60 years. Partial withdrawal allowed for specific purposes. Choice of investment options: Equity, Corporate Bonds, Government Securities. Tax benefits under Section 80C and 80CCD.",
            },
            {
                "name": "State Education Grant",
                "category": "Education",
                "scheme_type": "State Government",
                "description": "Grant for state students.",
                "s_eligibility": "12th Pass",
                "benefits": "Up to 50,000 INR.",
                "location": "Tamil Nadu",
                "date": date(2025, 7, 5),
                "additional_info": "For students pursuing higher education in Tamil Nadu. Family income limit: ₹2.5 lakh per annum. Covers tuition fees, hostel fees, and books. Application through e-District portal. Renewal based on academic performance.",
            },
            {
                "name": "Women Empowerment Loan",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan scheme for women entrepreneurs.",
                "s_eligibility": "Graduate",
                "benefits": "Low-interest loans up to 5 Lakhs.",
                "location": "Hyderabad",
                "date": date(2025, 5, 5),
                "additional_info": "Interest rate: 6-7% per annum. Moratorium period: 1 year. Repayment period: 7 years. Collateral-free. Business training and mentorship provided. Special focus on rural women entrepreneurs.",
            },
            {
                "name": "Youth Sports Development",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Support for young athletes.",
                "s_eligibility": "12th Pass",
                "benefits": "Scholarships and training support.",
                "location": "Delhi",
                "date": date(2025, 8, 5),
                "additional_info": "Monthly stipend: ₹5000-₹10000 based on performance. Training at SAI centers. Competition exposure at national and international levels. Educational support alongside sports training. Age limit: 14-25 years.",
            },
            {
                "name": "PM Awas Yojana",
                "category": "Housing",
                "scheme_type": "Central Government",
                "description": "Housing for all scheme.",
                "s_eligibility": "18+ years, Low Income",
                "benefits": "Subsidy on home loans.",
                "location": "All India",
                "date": date(2025, 1, 15),
                "additional_info": "Interest subsidy: 6.5% for 20 years. Income limit: ₹3-18 lakh per annum based on location. Credit Linked Subsidy Scheme (CLSS) component. Application through PMAY-U or PMAY-G portal. Target: Housing for all by 2024.",
            },
            {
                "name": "Ujjwala Yojana",
                "category": "Welfare",
                "scheme_type": "Central Government",
                "description": "Free LPG connection for women.",
                "s_eligibility": "BPL Families",
                "benefits": "Free LPG connection.",
                "location": "All India",
                "date": date(2025, 4, 10),
                "additional_info": "One-time financial support of ₹1600 for LPG connection. EMI facility for stove and first refill. Identification through Socio-Economic Caste Census (SECC) data. Over 8 crore connections provided since launch. Reduced indoor air pollution.",
            },
            {
                "name": "PM Mudra Yojana",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for small businesses.",
                "s_eligibility": "18+ years",
                "benefits": "Loans up to 10 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 8),
                "additional_info": "Three categories: Shishu (up to ₹50,000), Kishore (₹50,000-₹5 lakh), Tarun (₹5-10 lakh). Collateral-free. Interest rate: 10-12% per annum. Application through banks, NBFCs, MFIs. Over 30 crore loans sanctioned.",
            },
            {
                "name": "Stand Up India",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for SC/ST and women entrepreneurs.",
                "s_eligibility": "SC/ST/Women",
                "benefits": "Loan from 10 Lakhs to 1 Crore.",
                "location": "All India",
                "date": date(2025, 3, 5),
                "additional_info": "Composite loan (term loan and working capital). Margin money: 25% of project cost. Repayment period: up to 7 years. RuPay debit card for working capital. Handholding support for 2 years.",
            },
            {
                "name": "PMEGP",
                "category": "Employment",
                "scheme_type": "Loan",
                "description": "Prime Minister Employment Generation Program.",
                "s_eligibility": "18+ years",
                "benefits": "Subsidy for self-employment.",
                "location": "All India",
                "date": date(2025, 4, 8),
                "additional_info": "Margin money subsidy: 25-35% of project cost. Maximum project cost: ₹25 lakh (manufacturing), ₹10 lakh (service). Application through KVIC, State KVIB, DIC. E-tracking of application status. Training provided before disbursement.",
            },
            {
                "name": "NRLM",
                "category": "Employment",
                "scheme_type": "Welfare",
                "description": "National Rural Livelihood Mission.",
                "s_eligibility": "Rural Population",
                "benefits": "Skill development and financial support.",
                "location": "Rural India",
                "date": date(2025, 1, 12),
                "additional_info": "Focus on women self-help groups. Revolving fund and community investment support. Interest subvention on bank loans. Skill development and placement. Market linkages for products. Over 7 crore women mobilized into SHGs.",
            },
            {
                "name": "NSAP",
                "category": "Welfare",
                "scheme_type": "Pension",
                "description": "National Social Assistance Programme.",
                "s_eligibility": "Senior Citizens, Widows, Disabled",
                "benefits": "Monthly pension.",
                "location": "All India",
                "date": date(2025, 4, 12),
                "additional_info": "Five components: IGNOAPS, IGNWPS, IGNDPS, NFBS, Annapurna. Pension amount: ₹200-500 per month. Identification through BPL list. Application through Gram Panchayat/Municipality. Direct Benefit Transfer to bank account.",
            },
            {
                "name": "PMJJBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Jeevan Jyoti Bima Yojana.",
                "s_eligibility": "18-50 years",
                "benefits": "Life insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 18),
                "additional_info": "Premium: ₹330 per year. Auto-debit from bank account. Risk coverage: ₹2 lakh for death due to any reason. No medical examination required. Available through banks and post offices. Over 10 crore enrolments.",
            },
            {
                "name": "PMSBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Suraksha Bima Yojana.",
                "s_eligibility": "18-70 years",
                "benefits": "Accidental insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 22),
                "additional_info": "Premium: ₹12 per year. Auto-debit from bank account. Risk coverage: ₹2 lakh for accidental death, ₹1 lakh for partial disability. Available through banks and post offices. Over 20 crore enrolments.",
            },
            {
                "name": "APY",
                "category": "Pension",
                "scheme_type": "Central Government",
                "description": "Atal Pension Yojana.",
                "s_eligibility": "18-40 years",
                "benefits": "Fixed pension after 60 years.",
                "location": "All India",
                "date": date(2025, 1, 25),
                "additional_info": "Pension options: ₹1000-5000 per month. Government co-contribution: 50% of contribution or ₹1000 per year (for 5 years). Auto-debit from bank account. Available through banks and post offices. Over 3 crore subscribers.",
            },
            {
                "name": "PMFBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Fasal Bima Yojana.",
                "s_eligibility": "Farmers",
                "benefits": "Crop insurance.",
                "location": "All India",
                "date": date(2025, 4, 15),
                "additional_info": "Premium: 2% (Kharif), 1.5% (Rabi), 5% (Commercial crops). Sum insured: Cost of cultivation. Claims settled within 2 weeks of cut-off date. Technology-based assessment using remote sensing. Over 5 crore farmer applications.",
            },
            {
                "name": "State Health Scheme",
                "category": "Health",
                "scheme_type": "State Government",
                "description": "Health insurance for state residents.",
                "s_eligibility": "State Residents",
                "benefits": "Health coverage up to 5 Lakhs.",
                "location": "Kerala",
                "date": date(2025, 6, 8),
                "additional_info": "Premium: ₹800 per year for family of four. Cashless treatment at empaneled hospitals. Covers pre-existing diseases from day one. Outpatient coverage included. Application through Akshaya centers or online portal.",
            },
            {
                "name": "Student Credit Card",
                "category": "Education",
                "scheme_type": "Loan",
                "description": "Education loan for students.",
                "s_eligibility": "12th Pass",
                "benefits": "Loan up to 10 Lakhs for education.",
                "location": "West Bengal",
                "date": date(2025, 5, 8),
                "additional_info": "Interest rate: 4% during study period, 8% after. Moratorium period: Course duration + 1 year. Repayment period: 15 years. Collateral-free up to ₹7.5 lakh. Application through Vidyasathi portal.",
            },
            {
                "name": "Kanyashree Prakalpa",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for girl students.",
                "s_eligibility": "Girl Students",
                "benefits": "Annual scholarship.",
                "location": "West Bengal",
                "date": date(2025, 4, 8),
                "additional_info": "K1: ₹1000 annually for unmarried girls 13-18 years studying. K2: ₹25,000 one-time for unmarried girls18+ years pursuing higher education. Family income limit: ₹1.2 lakh per annum. Application through Kanyashree portal. Over 60 lakh beneficiaries.",
            },
            {
                "name": "Rupashree Prakalpa",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial assistance for marriage of girls.",
                "s_eligibility": "Girls from BPL families",
                "benefits": "One-time financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 12),
                "additional_info": "Amount: ₹25,000. Age: 18+ years. Family income limit: ₹1.2 lakh per annum. Application through Gram Panchayat/Municipality. Documents needed: Age proof, income certificate, bank account details.",
            },
            {
                "name": "Yuvashree Arpan",
                "category": "Employment",
                "scheme_type": "Allowance",
                "description": "Unemployment allowance for youth.",
                "s_eligibility": "Graduate, Unemployed",
                "benefits": "Monthly allowance.",
                "location": "West Bengal",
                "date": date(2025, 5, 12),
                "additional_info": "Allowance: ₹1500 per month for 2 years. Registration at employment exchange mandatory. Family income limit: ₹2.5 lakh per annum. Application through employment exchange. Skill training provided alongside allowance.",
            },
            {
                "name": "Krishak Bandhu",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial support for farmers.",
                "s_eligibility": "Farmers",
                "benefits": "Annual financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 15),
                "additional_info": "Amount: ₹5000 per year (₹2500 each for Kharif and Rabi). Landholding criteria: Up to 2 hectares. Life insurance cover of ₹2 lakh for farmers 18-60 years. Application through Krishak Bandhu portal.",
            },
            {
                "name": "Swasthya Sathi",
                "category": "Health",
                "scheme_type": "Insurance",
                "description": "Health insurance for families.",
                "s_eligibility": "All Residents",
                "benefits": "Health coverage up to 5 Lakhs per family.",
                "location": "West Bengal",
                "date": date(2025, 1, 12),
                "additional_info": "Cashless treatment at empaneled hospitals. Covers pre-existing diseases from day one. No premium payment. Covers 5 family members per card. Application through Duare Sarkar camp or Swasthya Sathi portal.",
            },
            {
                "name": "Mukhyamantri Tirth Yatra Yojana",
                "category": "Welfare",
                "scheme_type": "State Government",
                "description": "Free pilgrimage for senior citizens.",
                "s_eligibility": "Senior Citizens",
                "benefits": "Free travel to religious places.",
                "location": "Delhi",
                "date": date(2025, 4, 18),
                "additional_info": "For senior citizens above 60 years. Covers travel, accommodation, food. Destinations: Ayodhya, Varanasi, Mathura, Amritsar, etc. Application through Delhi government portal. Medical certificate required.",
            },
            {
                "name": "Delhi Startup Policy",
                "category": "Entrepreneurship",
                "scheme_type": "Subsidy",
                "description": "Support for startups in Delhi.",
                "s_eligibility": "Startups registered in Delhi",
                "benefits": "Financial support and subsidies.",
                "location": "Delhi",
                "date": date(2025, 6, 12),
                "additional_info": "Seed funding up to ₹20 lakh. Reimbursement of patent filing costs. Interest subsidy on loans. Incubation support. Application through Delhi Startup portal. Focus on technology and innovation.",
            },
            {
                "name": "National Green Corps",
                "category": "Welfare",
                "scheme_type": "Welfare",
                "description": "Engaging youth in Welfareal conservation activities.",
                "s_eligibility": "Schools and Colleges",
                "benefits": "Funding for eco-clubs and Welfareal projects.",
                "location": "All India",
                "date": date(2025, 3, 20),
                "additional_info": "Also known as Eco-club scheme. Financial support: ₹5000 per school per year. Over 1 lakh schools participating. Activities: plantation drives, waste management, water conservation. Application through State Nodal Agency.",
            },
            {
                "name": "Green India Mission",
                "category": "Welfare",
                "scheme_type": "Welfare",
                "description": "Increasing forest cover and improving ecosystem services.",
                "s_eligibility": "Forest Departments, NGOs",
                "benefits": "Financial assistance for afforestation projects.",
                "location": "All India",
                "date": date(2025, 4, 22),
                "additional_info": "Target: 5 million hectares of forest cover increase. Focus on degraded forests. Community participation emphasized. Budget: ₹46,000 crore. Application through State Forest Departments. Monitoring through satellite imagery.",
            },
            {
                "name": "National Solar Mission",
                "category": "Welfare",
                "scheme_type": "Subsidy",
                "description": "Promoting solar energy adoption across India.",
                "s_eligibility": "Households, Institutions, Industries",
                "benefits": "Subsidies for solar panel installation.",
                "location": "All India",
                "date": date(2025, 5, 15),
                "additional_info": "Subsidy: 40% for systems up to 3kW, 20% for 3-10kW. Target: 100 GW solar capacity by 2022. Net metering facility. Application through National Portal for Rooftop Solar. EMI options available.",
            },
            {
                "name": "Swachh Bharat Fellowship",
                "category": "Welfare",
                "scheme_type": "Scholarship",
                "description": "Fellowship for youth working on sanitation projects.",
                "s_eligibility": "Graduate, Post Graduate",
                "benefits": "Monthly stipend and project funding.",
                "location": "All India",
                "date": date(2025, 6, 10),
                "additional_info": "Stipend: ₹20,000 per month for 1 year. Project funding: up to ₹5 lakh. Focus on innovative sanitation solutions. Application through Swachh Bharat Mission portal. Selection based on project proposal.",
            },
            {
                "name": "Eco-warrior Scholarship",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for students pursuing Welfareal studies.",
                "s_eligibility": "12th Pass",
                "benefits": "Tuition fee waiver and research grant.",
                "location": "All India",
                "date": date(2025, 7, 5),
                "additional_info": "Scholarship amount: ₹50,000 per year. Research grant: up to ₹1 lakh. For UG and PG courses in Welfareal science. Minimum 75% marks required. Application through Ministry of Welfare portal.",
            },
            {
                "name": "National Merit Scholarship",
                "category": "Scholarships",
                "scheme_type": "Merit-based",
                "description": "Scholarship for academically brilliant students from low-income families.",
                "s_eligibility": "12th Pass",
                "benefits": "Full tuition coverage and monthly stipend.",
                "location": "All India",
                "date": date(2025, 8, 1),
                "additional_info": "Monthly stipend: ₹2000 for UG, ₹3000 for PG. Family income limit: ₹6 lakh per annum. Renewal based on academic performance. Application through National Scholarship Portal. 82,000 scholarships awarded annually.",
            },
            {
                "name": "Prime Minister's Research Fellowship",
                "category": "Scholarships",
                "scheme_type": "Research",
                "description": "Fellowship for students pursuing PhD in STEM fields.",
                "s_eligibility": "Post Graduate",
                "benefits": "Monthly stipend of 70,000 INR for 5 years.",
                "location": "All India",
                "date": date(2025, 9, 15),
                "additional_info": "Contingency grant: ₹2 lakh per year. International research exposure. For PhD in IITs, IISc, NITs, IISERs, IIITs. 3000 fellowships to be awarded. Application through PMRF portal.",
            },
            {
                "name": "Sports Talent Search Scholarship",
                "category": "Scholarships",
                "scheme_type": "Sports",
                "description": "Scholarship for young athletes with exceptional talent.",
                "s_eligibility": "12th Pass",
                "benefits": "Training support and financial assistance.",
                "location": "All India",
                "date": date(2025, 10, 5),
                "additional_info": "Scholarship amount: ₹20,000-₹50,000 per year based on performance. Training at SAI centers. Competition participation support. Educational support. Application through Sports Authority of India.",
            },
            {
                "name": "Cultural Talent Search Scholarship",
                "category": "Scholarships",
                "scheme_type": "Arts",
                "description": "Scholarship for students excelling in performing arts.",
                "s_eligibility": "Graduate",
                "benefits": "Training support and performance opportunities.",
                "location": "All India",
                "date": date(2025, 11, 20),
                "additional_info": "Scholarship amount: ₹10,000-₹30,000 per year. Fields: music, dance, theater, visual arts. Training under gurus/eminent artists. Performance opportunities at national events. Application through Centre for Cultural Resources and Training.",
            },
            {
                "name": "Single Girl Child Scholarship",
                "category": "Scholarships",
                "scheme_type": "Gender-based",
                "description": "Scholarship for single girl children pursuing higher education.",
                "s_eligibility": "Girl Students",
                "benefits": "Full tuition fee waiver and hostel charges.",
                "location": "All India",
                "date": date(2025, 12, 10),
                "additional_info": "For UG and PG courses. Additional monthly allowance: ₹3000. Age limit: below 30 years. Application through University Grants Commission. 3000 scholarships awarded annually.",
            },
            {
                "name": "SC/ST Post-Matric Scholarship",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Scholarship for SC/ST students pursuing post-matric education.",
                "s_eligibility": "SC/ST/Women",
                "benefits": "Maintenance allowance and tuition fees.",
                "location": "All India",
                "date": date(2025, 1, 30),
                "additional_info": "Maintenance allowance: ₹230-₹1200 per month based on course. Tuition fees: actual up to ₹10,000 per year. Additional allowances for books, travel. Application through National Scholarship Portal. 100% digital application process.",
            },
            {
                "name": "OBC Scholarship Scheme",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Financial assistance for OBC students pursuing higher education.",
                "s_eligibility": "BPL Families",
                "benefits": "Maintenance allowance and tuition fees.",
                "location": "All India",
                "date": date(2025, 2, 25),
                "additional_info": "Maintenance allowance: ₹350-₹750 per month based on course. Tuition fees: actual up to ₹10,000 per year. Hostel charges: ₹500 per month. Application through National Scholarship Portal. OBC certificate mandatory.",
            },
            {
                "name": "Minority Scholarship",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Scholarship for students from minority communities.",
                "s_eligibility": "BPL Families",
                "benefits": "Tuition fees and maintenance allowance.",
                "location": "All India",
                "date": date(2025, 3, 15),
                "additional_info": "Pre-matric: ₹1000-₹5000 per year. Post-matric: ₹7000-₹12000 per year. Merit-cum-means scholarship for professional courses: ₹20,000 per year. Application through National Scholarship Portal. Minority community certificate required.",
            },
            {
                "name": "Differently-abled Student Scholarship",
                "category": "Scholarships",
                "scheme_type": "Inclusive Education",
                "description": "Scholarship for students with disabilities pursuing education.",
                "s_eligibility": "12th Pass",
                "benefits": "Tuition fees, books, and assistive devices.",
                "location": "All India",
                "date": date(2025, 4, 20),
                "additional_info": "Scholarship amount: ₹1000-₹2000 per month based on course. Reader allowance for blind students: ₹2400 per month. Escort allowance for severely disabled: ₹3000 per month. Application through National Scholarship Portal. Disability certificate required.",
            },
            {
                "name": "Waste Management Innovation Grant",
                "category": "Welfare",
                "scheme_type": "Innovation",
                "description": "Grant for innovative waste management solutions.",
                "s_eligibility": "Startups, NGOs, Researchers",
                "benefits": "Funding up to 50 Lakhs for project implementation.",
                "location": "All India",
                "date": date(2025, 5, 25),
                "additional_info": "Focus on plastic waste, e-waste, biomedical waste. Grant disbursed in milestones. Technical mentorship provided. IP rights with innovator. Application through Ministry of Welfare portal. Selection based on innovation and impact.",
            },
            {
                "name": "Water Conservation Fellowship",
                "category": "Welfare",
                "scheme_type": "Scholarship",
                "description": "Fellowship for research on water conservation techniques.",
                "s_eligibility": "MTech/PhD in Welfareal Science",
                "benefits": "Monthly stipend and research grant.",
                "location": "All India",
                "date": date(2025, 6, 15),
                "additional_info": "Stipend: ₹50,000 per month for 2 years. Research grant: ₹5 lakh. Focus on rainwater harvesting, groundwater recharge, wastewater reuse. Field implementation required. Application through National Water Mission.",
            },
            {
                "name": "Climate Change Research Grant",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Grant for research projects on climate change mitigation.",
                "s_eligibility": "Research Institutions, Universities",
                "benefits": "Funding up to 1 Crore for research projects.",
                "location": "All India",
                "date": date(2025, 7, 20),
                "additional_info": "Focus on renewable energy, carbon sequestration, climate resilience. Duration: 2-3 years. Interdisciplinary projects encouraged. Collaboration with international institutions supported. Application through Department of Science and Technology.",
            },
            {
                "name": "Organic Farming Subsidy",
                "category": "Welfare",
                "scheme_type": "Subsidy",
                "description": "Subsidy for farmers adopting organic farming practices.",
                "s_eligibility": "Farmers with minimum 1 acre land",
                "benefits": "50% subsidy on organic inputs and certification.",
                "location": "All India",
                "date": date(2025, 8, 10),
                "additional_info": "Subsidy limit: ₹10,000 per hectare for 3 years. Certification cost covered under PKVY scheme. Training on organic practices provided. Market linkage through Jaivik Kheti portal. Application through State Agriculture Department.",
            },
            {
                "name": "Electric Vehicle Adoption Incentive",
                "category": "Welfare",
                "scheme_type": "Subsidy",
                "description": "Financial incentive for purchasing electric vehicles.",
                "s_eligibility": "Individual buyers, Fleet operators",
                "benefits": "Up to 1.5 Lakh subsidy on electric vehicles.",
                "location": "All India",
                "date": date(2025, 9, 5),
                "additional_info": "Subsidy under FAME India Scheme. Additional state subsidies available. Road tax exemption in many states. Charging infrastructure development ongoing. Application through vehicle dealer at time of purchase.",
            },
            {
                "name": "Renewable Energy Startup Fund",
                "category": "Entrepreneurship",
                "scheme_type": "Financial Assistance",
                "description": "Funding for startups working in renewable energy sector.",
                "s_eligibility": "Registered startups in renewable energy",
                "benefits": "Seed funding up to 2 Crores and mentorship.",
                "location": "All India",
                "date": date(2025, 10, 15),
                "additional_info": "Focus on solar, wind, biomass, small hydro. Equity investment or convertible debt. Mentorship from industry experts. Incubation support. Application through Startup India portal. Selection based on innovation and scalability.",
            }
        ]

        for scheme_data in schemes:
            scheme, created = Scheme.objects.update_or_create(
                name=scheme_data["name"], defaults=scheme_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Scheme created: {scheme.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Scheme updated: {scheme.name}"))