from django.core.management.base import BaseCommand
from my_app.models import Exam, Scheme
from datetime import date, timedelta


class Command(BaseCommand):
    help = "Seed the database with initial Exam and Scheme data"

    def handle(self, *args, **kwargs):
        # -------- Exams --------
        exams = [
            {
                "name": "JEE Main",
                "exam_type": "Government",
                "category": "Engineering",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 1, 6),  # Using exam_date as the single date field
            },
            {
                "name": "NEET",
                "exam_type": "Government",
                "category": "Medical",
                "location": "All India",
                "mode": "Offline",
                "date": date(2025, 5, 7),
            },
            {
                "name": "UPSC Civil Services",
                "exam_type": "Government",
                "category": "Civil Services",
                "location": "Delhi",
                "mode": "Offline",
                "date": date(2025, 5, 28),
            },
            {
                "name": "CAT",
                "exam_type": "National Level",
                "category": "Management",
                "location": "Mumbai",
                "mode": "Online",
                "date": date(2025, 11, 24),
            },
            {
                "name": "GATE",
                "exam_type": "National Level",
                "category": "Engineering",
                "location": "Bengaluru",
                "mode": "Online",
                "date": date(2025, 2, 8),
            },
            {
                "name": "CLAT",
                "exam_type": "National Level",
                "category": "Law",
                "location": "Hyderabad",
                "mode": "Offline",
                "date": date(2025, 12, 8),
            },
            {
                "name": "SSC CGL",
                "exam_type": "Government",
                "category": "Employment",
                "location": "Chennai",
                "mode": "Online",
                "date": date(2025, 7, 14),
            },
            {
                "name": "IBPS PO",
                "exam_type": "Government",
                "category": "Banking",
                "location": "West Bengal",
                "mode": "Online",
                "date": date(2025, 9, 20),
            },
            {
                "name": "NDA",
                "exam_type": "Government",
                "category": "Defense",
                "location": "Delhi",
                "mode": "Offline",
                "date": date(2025, 4, 14),
            },
            {
                "name": "NET",
                "exam_type": "Government",
                "category": "Teaching",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 12, 5),
            },
            {
                "name": "AIIMS MBBS",
                "exam_type": "Government",
                "category": "Medical",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 5, 20),
            },
            {
                "name": "IIT JAM",
                "exam_type": "National Level",
                "category": "Science",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 2, 10),
            },
            {
                "name": "NIFT",
                "exam_type": "National Level",
                "category": "Design",
                "location": "Mumbai",
                "mode": "Offline",
                "date": date(2025, 2, 18),
            },
            {
                "name": "NID",
                "exam_type": "National Level",
                "category": "Design",
                "location": "Ahmedabad",
                "mode": "Offline",
                "date": date(2025, 1, 8),
            },
            {
                "name": "IIFT",
                "exam_type": "National Level",
                "category": "Management",
                "location": "Delhi",
                "mode": "Online",
                "date": date(2024, 11, 28),
            },
            {
                "name": "XAT",
                "exam_type": "National Level",
                "category": "Management",
                "location": "Multiple Cities",
                "mode": "Online",
                "date": date(2025, 1, 3),
            },
            {
                "name": "MAT",
                "exam_type": "National Level",
                "category": "Management",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 2, 12),
            },
            {
                "name": "SSC CHSL",
                "exam_type": "Government",
                "category": "Employment",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 4, 12),
            },
            {
                "name": "SSC JE",
                "exam_type": "Government",
                "category": "Engineering",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 7, 1),
            },
            {
                "name": "SSC GD",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 4, 5),
            },
            {
                "name": "RBI Grade B",
                "exam_type": "Government",
                "category": "Banking",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 7, 28),
            },
            {
                "name": "SBI PO",
                "exam_type": "Government",
                "category": "Banking",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 12),
            },
            {
                "name": "SBI Clerk",
                "exam_type": "Government",
                "category": "Banking",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 28),
            },
            {
                "name": "IBPS Clerk",
                "exam_type": "Government",
                "category": "Banking",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 10, 30),
            },
            {
                "name": "IBPS RRB",
                "exam_type": "Government",
                "category": "Banking",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 8, 10),
            },
            {
                "name": "LIC AAO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 5, 5),
            },
            {
                "name": "LIC ADO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 1),
            },
            {
                "name": "NICL AO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 25),
            },
            {
                "name": "UIIC AO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 7, 28),
            },
            {
                "name": "NIACL AO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 9, 1),
            },
            {
                "name": "FCI",
                "exam_type": "Government",
                "category": "Food Corporation",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 3, 30),
            },
            {
                "name": "CISF",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 4, 28),
            },
            {
                "name": "CRPF",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 5),
            },
            {
                "name": "BSF",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 7, 10),
            },
            {
                "name": "ITBP",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 8, 15),
            },
            {
                "name": "CDS",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Offline",
                "date": date(2025, 2, 15),
            },
            {
                "name": "AFCAT",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 8, 20),
            },
            {
                "name": "INET",
                "exam_type": "Government",
                "category": "Defense",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 9, 5),
            },
            {
                "name": "ESIC SSO",
                "exam_type": "Government",
                "category": "Insurance",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 9, 28),
            },
            {
                "name": "EPFO SSA",
                "exam_type": "Government",
                "category": "Employment",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 10, 30),
            },
            {
                "name": "EPFO AO",
                "exam_type": "Government",
                "category": "Employment",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 12, 5),
            },
            {
                "name": "NTA UGC NET",
                "exam_type": "Government",
                "category": "Teaching",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 6, 15),
            },
            {
                "name": "CSIR UGC NET",
                "exam_type": "Government",
                "category": "Science",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 7, 5),
            },
            {
                "name": "ICAR AIEEA",
                "exam_type": "Government",
                "category": "Agriculture",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 5, 20),
            },
            {
                "name": "NCHMCT JEE",
                "exam_type": "National Level",
                "category": "Hotel Management",
                "location": "All India",
                "mode": "Online",
                "date": date(2025, 5, 25),
            },
            {
                "name": "IIIT Hyderabad Entrance",
                "exam_type": "University Level",
                "category": "Engineering",
                "location": "Hyderabad",
                "mode": "Online",
                "date": date(2025, 4, 10),
            },
            {
                "name": "BITSAT",
                "exam_type": "University Level",
                "category": "Engineering",
                "location": "Multiple Cities",
                "mode": "Online",
                "date": date(2025, 6, 15),
            },
            {
                "name": "VITEEE",
                "exam_type": "University Level",
                "category": "Engineering",
                "location": "Vellore",
                "mode": "Online",
                "date": date(2025, 4, 10),
            },
            {
                "name": "SRMJEEE",
                "exam_type": "University Level",
                "category": "Engineering",
                "location": "Chennai",
                "mode": "Online",
                "date": date(2025, 5, 1),
            },
            {
                "name": "KIITEE",
                "exam_type": "University Level",
                "category": "Engineering",
                "location": "Bhubaneswar",
                "mode": "Online",
                "date": date(2025, 4, 5),
            },
            {
                "name": "COMEDK",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Karnataka",
                "mode": "Online",
                "date": date(2025, 5, 10),
            },
            {
                "name": "KCET",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Karnataka",
                "mode": "Offline",
                "date": date(2025, 4, 15),
            },
            {
                "name": "MHT CET",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Maharashtra",
                "mode": "Online",
                "date": date(2025, 5, 1),
            },
            {
                "name": "TS EAMCET",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Telangana",
                "mode": "Online",
                "date": date(2025, 5, 5),
            },
            {
                "name": "AP EAMCET",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Andhra Pradesh",
                "mode": "Online",
                "date": date(2025, 5, 10),
            },
            {
                "name": "WBJEE",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "West Bengal",
                "mode": "Offline",
                "date": date(2025, 4, 25),
            },
            {
                "name": "OJEE",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Odisha",
                "mode": "Online",
                "date": date(2025, 5, 3),
            },
            {
                "name": "GUJCET",
                "exam_type": "State Level",
                "category": "Engineering",
                "location": "Gujarat",
                "mode": "Offline",
                "date": date(2025, 4, 10),
            },
            {
                "name": "CGPSC",
                "exam_type": "State Level",
                "category": "Civil Services",
                "location": "Chhattisgarh",
                "mode": "Offline",
                "date": date(2025, 6, 10),
            },
            {
                "name": "MPPSC",
                "exam_type": "State Level",
                "category": "Civil Services",
                "location": "Madhya Pradesh",
                "mode": "Offline",
                "date": date(2025, 6, 28),
            },
            {
                "name": "TNPSC",
                "exam_type": "State Level",
                "category": "Civil Services",
                "location": "Tamil Nadu",
                "mode": "Online",
                "date": date(2025, 8, 1),
            },
            {
                "name": "UKPSC",
                "exam_type": "State Level",
                "category": "Civil Services",
                "location": "Uttarakhand",
                "mode": "Online",
                "date": date(2025, 8, 28),
            },
        ]

        for exam_data in exams:
            exam, created = Exam.objects.update_or_create(
                name=exam_data["name"], defaults=exam_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Exam created: {exam.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Exam updated: {exam.name}"))

        # -------- Schemes --------
        schemes = [
            {
                "name": "Central Scholarship Scheme",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for meritorious students.",
                "eligibility": "12th Pass",
                "benefits": "Covers tuition fees and stipend.",
                "location": "All India",
                "date": date(2025, 4, 5),  # Using start_date as the single date field
            },
            {
                "name": "Startup India Loan",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Financial support for startups.",
                "eligibility": "Graduate",
                "benefits": "Low-interest loan up to 10 Lakhs.",
                "location": "Delhi",
                "date": date(2025, 1, 10),
            },
            {
                "name": "Ayushman Bharat",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Healthcare scheme for low-income families.",
                "eligibility": "10th Pass",
                "benefits": "Free health coverage up to 5 Lakhs.",
                "location": "All India",
                "date": date(2025, 3, 15),
            },
            {
                "name": "PM Kisan Samman Nidhi",
                "category": "Employment",
                "scheme_type": "Central Government",
                "description": "Income support for farmers.",
                "eligibility": "10th Pass",
                "benefits": "6000 INR per year.",
                "location": "West Bengal",
                "date": date(2025, 2, 5),
            },
            {
                "name": "Skill India Mission",
                "category": "Employment",
                "scheme_type": "Training",
                "description": "Skill development for youth.",
                "eligibility": "12th Pass",
                "benefits": "Free training programs.",
                "location": "Mumbai",
                "date": date(2025, 6, 5),
            },
            {
                "name": "Digital India Initiative",
                "category": "General",
                "scheme_type": "Central Government",
                "description": "Promoting digital infrastructure.",
                "eligibility": "Graduate",
                "benefits": "Support for digital adoption.",
                "location": "Bengaluru",
                "date": date(2025, 1, 20),
            },
            {
                "name": "National Pension Scheme",
                "category": "Finance",
                "scheme_type": "Central Government",
                "description": "Retirement savings scheme.",
                "eligibility": "Graduate",
                "benefits": "Tax benefits and pension.",
                "location": "All India",
                "date": date(2025, 1, 5),
            },
            {
                "name": "State Education Grant",
                "category": "Education",
                "scheme_type": "State Government",
                "description": "Grant for state students.",
                "eligibility": "12th Pass",
                "benefits": "Up to 50,000 INR.",
                "location": "Chennai",
                "date": date(2025, 7, 5),
            },
            {
                "name": "Women Empowerment Loan",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan scheme for women entrepreneurs.",
                "eligibility": "Graduate",
                "benefits": "Low-interest loans up to 5 Lakhs.",
                "location": "Hyderabad",
                "date": date(2025, 5, 5),
            },
            {
                "name": "Youth Sports Development",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Support for young athletes.",
                "eligibility": "12th Pass",
                "benefits": "Scholarships and training support.",
                "location": "Delhi",
                "date": date(2025, 8, 5),
            },
            {
                "name": "PM Awas Yojana",
                "category": "Housing",
                "scheme_type": "Central Government",
                "description": "Housing for all scheme.",
                "eligibility": "18+ years, Low Income",
                "benefits": "Subsidy on home loans.",
                "location": "All India",
                "date": date(2025, 1, 15),
            },
            {
                "name": "Ujjwala Yojana",
                "category": "Welfare",
                "scheme_type": "Central Government",
                "description": "Free LPG connection for women.",
                "eligibility": "BPL Families",
                "benefits": "Free LPG connection.",
                "location": "All India",
                "date": date(2025, 4, 10),
            },
            {
                "name": "PM Mudra Yojana",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for small businesses.",
                "eligibility": "18+ years",
                "benefits": "Loans up to 10 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 8),
            },
            {
                "name": "Stand Up India",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for SC/ST and women entrepreneurs.",
                "eligibility": "SC/ST/Women",
                "benefits": "Loan from 10 Lakhs to 1 Crore.",
                "location": "All India",
                "date": date(2025, 3, 5),
            },
            {
                "name": "PMEGP",
                "category": "Employment",
                "scheme_type": "Loan",
                "description": "Prime Minister Employment Generation Program.",
                "eligibility": "18+ years",
                "benefits": "Subsidy for self-employment.",
                "location": "All India",
                "date": date(2025, 4, 8),
            },
            {
                "name": "NRLM",
                "category": "Employment",
                "scheme_type": "Welfare",
                "description": "National Rural Livelihood Mission.",
                "eligibility": "Rural Population",
                "benefits": "Skill development and financial support.",
                "location": "Rural India",
                "date": date(2025, 1, 12),
            },
            {
                "name": "NSAP",
                "category": "Welfare",
                "scheme_type": "Pension",
                "description": "National Social Assistance Programme.",
                "eligibility": "Senior Citizens, Widows, Disabled",
                "benefits": "Monthly pension.",
                "location": "All India",
                "date": date(2025, 4, 12),
            },
            {
                "name": "PMJJBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Jeevan Jyoti Bima Yojana.",
                "eligibility": "18-50 years",
                "benefits": "Life insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 18),
            },
            {
                "name": "PMSBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Suraksha Bima Yojana.",
                "eligibility": "18-70 years",
                "benefits": "Accidental insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 22),
            },
            {
                "name": "APY",
                "category": "Pension",
                "scheme_type": "Central Government",
                "description": "Atal Pension Yojana.",
                "eligibility": "18-40 years",
                "benefits": "Fixed pension after 60 years.",
                "location": "All India",
                "date": date(2025, 1, 25),
            },
            {
                "name": "PMFBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Fasal Bima Yojana.",
                "eligibility": "Farmers",
                "benefits": "Crop insurance.",
                "location": "All India",
                "date": date(2025, 4, 15),
            },
            {
                "name": "State Health Scheme",
                "category": "Health",
                "scheme_type": "State Government",
                "description": "Health insurance for state residents.",
                "eligibility": "State Residents",
                "benefits": "Health coverage up to 5 Lakhs.",
                "location": "Kerala",
                "date": date(2025, 6, 8),
            },
            {
                "name": "Student Credit Card",
                "category": "Education",
                "scheme_type": "Loan",
                "description": "Education loan for students.",
                "eligibility": "12th Pass",
                "benefits": "Loan up to 10 Lakhs for education.",
                "location": "West Bengal",
                "date": date(2025, 5, 8),
            },
            {
                "name": "Kanyashree Prakalpa",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for girl students.",
                "eligibility": "Girl Students",
                "benefits": "Annual scholarship.",
                "location": "West Bengal",
                "date": date(2025, 4, 8),
            },
            {
                "name": "Rupashree Prakalpa",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial assistance for marriage of girls.",
                "eligibility": "Girls from BPL families",
                "benefits": "One-time financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 12),
            },
            {
                "name": "Yuvashree Arpan",
                "category": "Employment",
                "scheme_type": "Allowance",
                "description": "Unemployment allowance for youth.",
                "eligibility": "Graduate, Unemployed",
                "benefits": "Monthly allowance.",
                "location": "West Bengal",
                "date": date(2025, 5, 12),
            },
            {
                "name": "Krishak Bandhu",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial support for farmers.",
                "eligibility": "Farmers",
                "benefits": "Annual financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 15),
            },
            {
                "name": "Swasthya Sathi",
                "category": "Health",
                "scheme_type": "Insurance",
                "description": "Health insurance for families.",
                "eligibility": "All Residents",
                "benefits": "Health coverage up to 5 Lakhs per family.",
                "location": "West Bengal",
                "date": date(2025, 1, 12),
            },
            {
                "name": "Mukhyamantri Tirth Yatra Yojana",
                "category": "Welfare",
                "scheme_type": "State Government",
                "description": "Free pilgrimage for senior citizens.",
                "eligibility": "Senior Citizens",
                "benefits": "Free travel to religious places.",
                "location": "Delhi",
                "date": date(2025, 4, 18),
            },
            {
                "name": "Delhi Startup Policy",
                "category": "Finance",
                "scheme_type": "Subsidy",
                "description": "Support for startups in Delhi.",
                "eligibility": "Startups registered in Delhi",
                "benefits": "Financial support and subsidies.",
                "location": "Delhi",
                "date": date(2025, 6, 12),
            },
        ]

        for scheme_data in schemes:
            scheme, created = Scheme.objects.update_or_create(
                name=scheme_data["name"], defaults=scheme_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Scheme created: {scheme.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Scheme updated: {scheme.name}"))
