# Generated by Django 5.2 on 2025-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_userprofile_gender_userprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
