# Generated by Django 5.2 on 2025-08-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_scheme_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('All India', 'All India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Health', 'Health'), ('Finance', 'Finance'), ('General', 'General'), ('Entrepreneurship', 'Entrepreneurship')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('Open to All', 'Open to All')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Kerala', 'Kerala'), ('Rajasthan', 'Rajasthan'), ('All India', 'All India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Welfare', 'Welfare'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan'), ('Employment', 'Employment')], default='Central Government', max_length=50),
        ),
    ]
