# Generated by Django 5.2 on 2025-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_exam_exam_date_exam_form_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='form_last_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management'), ('Science', 'Science'), ('Design', 'Design'), ('Employment', 'Employment'), ('Insurance', 'Insurance'), ('Food Corporation', 'Food Corporation'), ('Agriculture', 'Agriculture'), ('Hotel Management', 'Hotel Management')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('University Level', 'University Level')], default='Government', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Bhubaneswar', 'Bhubaneswar'), ('Vellore', 'Vellore'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Health', 'Health'), ('Finance', 'Finance'), ('General', 'General'), ('Entrepreneurship', 'Entrepreneurship'), ('Housing', 'Housing'), ('Welfare', 'Welfare'), ('Insurance', 'Insurance'), ('Pension', 'Pension'), ('Food Corporation', 'Food Corporation')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('Open to All', 'Open to All'), ('18+ years', '18+ years'), ('18-50 years', '18-50 years'), ('18-70 years', '18-70 years'), ('18-40 years', '18-40 years'), ('Senior Citizens', 'Senior Citizens'), ('BPL Families', 'BPL Families'), ('SC/ST/Women', 'SC/ST/Women'), ('Rural Population', 'Rural Population'), ('Farmers', 'Farmers'), ('State Residents', 'State Residents'), ('Girl Students', 'Girl Students'), ('Girls from BPL families', 'Girls from BPL families'), ('Graduate, Unemployed', 'Graduate, Unemployed'), ('All Residents', 'All Residents'), ('Startups registered in Delhi', 'Startups registered in Delhi'), ('Low Income', 'Low Income')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('All India', 'All India'), ('Kerala', 'Kerala'), ('Rural India', 'Rural India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Welfare', 'Welfare'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan'), ('Employment', 'Employment'), ('Training', 'Training'), ('Pension', 'Pension'), ('Insurance', 'Insurance'), ('Financial Assistance', 'Financial Assistance'), ('Subsidy', 'Subsidy'), ('Allowance', 'Allowance')], default='Central Government', max_length=50),
        ),
    ]
