# Generated by Django 5.2.4 on 2025-08-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_rename_end_date_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Bhubaneswar', 'Bhubaneswar'), ('Vellore', 'Vellore'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India')], default='All India', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Bengaluru', 'Bengaluru'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Bhubaneswar', 'Bhubaneswar'), ('Vellore', 'Vellore'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India')], default='All India', max_length=100),
        ),
    ]
