# Generated by Django 5.2 on 2025-08-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_rename_eligibility_scheme_s_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_eligibility',
            field=models.CharField(choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=20),
        ),
    ]
