# Generated by Django 5.2 on 2025-08-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_alter_exam_e_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Defense', 'Defense'), ('Civil Services', 'Civil Services'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Management', 'Management'), ('Science', 'Science'), ('Design', 'Design'), ('Employment', 'Employment'), ('Insurance', 'Insurance'), ('Food Corporation', 'Food Corporation'), ('Agriculture', 'Agriculture'), ('Hotel Management', 'Hotel Management'), ('Environment', 'Environment')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('University Level', 'University Level'), ('Professional', 'Professional')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India'), ('Coastal Cities', 'Coastal Cities')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Employment', 'Employment'), ('Health', 'Health'), ('Finance', 'Finance'), ('General', 'General'), ('Entrepreneurship', 'Entrepreneurship'), ('Housing', 'Housing'), ('Welfare', 'Welfare'), ('Insurance', 'Insurance'), ('Pension', 'Pension'), ('Food Corporation', 'Food Corporation')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Hyderabad', 'Hyderabad'), ('Tamil Nadu', 'Tamil Nadu'), ('All India', 'All India'), ('Multiple Cities', 'Multiple Cities'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Ahmedabad', 'Ahmedabad'), ('Rural India', 'Rural India')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central Government', 'Central Government'), ('State Government', 'State Government'), ('Welfare', 'Welfare'), ('Scholarship', 'Scholarship'), ('Loan', 'Loan'), ('Employment', 'Employment'), ('Training', 'Training'), ('Pension', 'Pension'), ('Insurance', 'Insurance'), ('Financial Assistance', 'Financial Assistance'), ('Subsidy', 'Subsidy'), ('Allowance', 'Allowance')], default='None', max_length=50),
        ),
    ]
