# Generated by Django 5.2.3 on 2025-06-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exam_scheme_taxupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caste_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
