from django.core.management.base import BaseCommand
from my_app.models import Exam, Scheme
from datetime import date, timedelta


class Command(BaseCommand):
    help = "Seed the database with initial Exam and Scheme data"

    def handle(self, *args, **kwargs):
        # -------- Exams --------
        from datetime import date

        exams = [
                {
                    "name": "JEE Main",
                    "exam_type": "Government",
                    "category": "Engineering",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 1, 6),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "NEET",
                    "exam_type": "Government",
                    "category": "Medical",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 5, 7),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "UPSC Civil Services",
                    "exam_type": "Government",
                    "category": "Civil Services",
                    "location": "Delhi",
                    "mode": "Offline",
                    "date": date(2025, 5, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "CAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 11, 24),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "GATE",
                    "exam_type": "National Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 2, 8),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "CLAT",
                    "exam_type": "National Level",
                    "category": "Law",
                    "location": "Hyderabad",
                    "mode": "Offline",
                    "date": date(2025, 12, 8),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "SSC CGL",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 7, 14),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "IBPS PO",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "West Bengal",
                    "mode": "Online",
                    "date": date(2025, 9, 20),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NDA",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "Delhi",
                    "mode": "Offline",
                    "date": date(2025, 4, 14),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "NET",
                    "exam_type": "Government",
                    "category": "Teaching",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 12, 5),
                    "e_eligibility": "Post Graduate",
                },
                {
                    "name": "AIIMS MBBS",
                    "exam_type": "Government",
                    "category": "Medical",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 20),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "IIT JAM",
                    "exam_type": "National Level",
                    "category": "Science",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 2, 10),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NIFT",
                    "exam_type": "National Level",
                    "category": "Design",
                    "location": "Maharashtra",
                    "mode": "Offline",
                    "date": date(2025, 2, 18),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NID",
                    "exam_type": "National Level",
                    "category": "Design",
                    "location": "Ahmedabad",
                    "mode": "Offline",
                    "date": date(2025, 1, 8),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "IIFT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2024, 11, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "XAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 1, 3),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "MAT",
                    "exam_type": "National Level",
                    "category": "Management",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 2, 12),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "SSC CHSL",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 12),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "SSC JE",
                    "exam_type": "Government",
                    "category": "Engineering",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 1),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "SSC GD",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 5),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "RBI Grade B",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "SBI PO",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 12),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "SBI Clerk",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "IBPS Clerk",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 10, 30),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "IBPS RRB",
                    "exam_type": "Government",
                    "category": "Banking",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 10),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "LIC AAO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 5),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "LIC ADO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 1),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NICL AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 25),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "UIIC AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NIACL AO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 1),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "FCI",
                    "exam_type": "Government",
                    "category": "Food Corporation",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 30),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "CISF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 28),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "CRPF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 5),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "BSF",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 10),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "ITBP",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 15),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "CDS",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 2, 15),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "AFCAT",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 8, 20),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "INET",
                    "exam_type": "Government",
                    "category": "Defense",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 5),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "ESIC SSO",
                    "exam_type": "Government",
                    "category": "Insurance",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "EPFO SSA",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 10, 30),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "EPFO AO",
                    "exam_type": "Government",
                    "category": "Employment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 12, 5),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "NTA UGC NET",
                    "exam_type": "Government",
                    "category": "Teaching",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 6, 15),
                    "e_eligibility": "Post Graduate",
                },
                {
                    "name": "CSIR UGC NET",
                    "exam_type": "Government",
                    "category": "Science",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 7, 5),
                    "e_eligibility": "Post Graduate",
                },
                {
                    "name": "ICAR AIEEA",
                    "exam_type": "Government",
                    "category": "Agriculture",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 20),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "NCHMCT JEE",
                    "exam_type": "National Level",
                    "category": "Hotel Management",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 5, 25),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "IIIT Hyderabad Entrance",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Hyderabad",
                    "mode": "Online",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "BITSAT",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 6, 15),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "VITEEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "SRMJEEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 5, 1),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "KIITEE",
                    "exam_type": "University Level",
                    "category": "Engineering",
                    "location": "Odisha",
                    "mode": "Online",
                    "date": date(2025, 4, 5),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "COMEDK",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "KCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Karnataka",
                    "mode": "Offline",
                    "date": date(2025, 4, 15),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "MHT CET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 5, 1),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "TS EAMCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Telangana",
                    "mode": "Online",
                    "date": date(2025, 5, 5),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "AP EAMCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Andhra Pradesh",
                    "mode": "Online",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "WBJEE",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "West Bengal",
                    "mode": "Offline",
                    "date": date(2025, 4, 25),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "OJEE",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Odisha",
                    "mode": "Online",
                    "date": date(2025, 5, 3),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "GUJCET",
                    "exam_type": "State Level",
                    "category": "Engineering",
                    "location": "Gujarat",
                    "mode": "Offline",
                    "date": date(2025, 4, 10),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "CGPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Chhattisgarh",
                    "mode": "Offline",
                    "date": date(2025, 6, 10),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "MPPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Madhya Pradesh",
                    "mode": "Offline",
                    "date": date(2025, 6, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "TNPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 8, 1),
                    "e_eligibility": "Post Graduate",
                },
                {
                    "name": "UKPSC",
                    "exam_type": "State Level",
                    "category": "Civil Services",
                    "location": "Uttarakhand",
                    "mode": "Online",
                    "date": date(2025, 8, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "National Environment Awareness Test",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 15),
                    "e_eligibility": "10th Pass",
                },
                {
                    "name": "Green Skills Certification Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 4, 22),
                    "e_eligibility": "12th Pass",
                },
                {
                    "name": "Climate Change National Level Certification",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Multiple Cities",
                    "mode": "Offline",
                    "date": date(2025, 5, 10),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Renewable Energy Engineer Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2025, 6, 5),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Environmental Impact Assessment Exam",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "Kerala",
                    "mode": "Online",
                    "date": date(2025, 7, 20),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Wildlife Conservation Officer Exam",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 8, 12),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Sustainable Development Certification",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 9, 8),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Forest Officer Recruitment Exam",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 10, 15),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Water Resource Management Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Tamil Nadu",
                    "mode": "Online",
                    "date": date(2025, 11, 5),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Environmental Science Olympiad",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Multiple Cities",
                    "mode": "Offline",
                    "date": date(2025, 12, 10),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Pollution Control Board Exam",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 1, 25),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Eco-Auditor Certification",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Maharashtra",
                    "mode": "Online",
                    "date": date(2025, 2, 18),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Biodiversity Conservation Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 3, 22),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Climate Analyst Certification",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Hyderabad",
                    "mode": "Online",
                    "date": date(2025, 4, 30),
                    "e_eligibility": "Post Graduate",
                },
                {
                    "name": "Environmental Law Entrance Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Offline",
                    "date": date(2025, 5, 25),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Waste Management National Level Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Delhi",
                    "mode": "Online",
                    "date": date(2025, 6, 20),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Green Building Consultant Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Karnataka",
                    "mode": "Online",
                    "date": date(2025, 7, 15),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Marine Conservation Officer Exam",
                    "exam_type": "Government",
                    "category": "Environment",
                    "location": "Coastal Cities",
                    "mode": "Offline",
                    "date": date(2025, 8, 28),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Environmental Education Certification",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "All India",
                    "mode": "Online",
                    "date": date(2025, 9, 20),
                    "e_eligibility": "Graduate",
                },
                {
                    "name": "Carbon Footprint Analyst Exam",
                    "exam_type": "National Level",
                    "category": "Environment",
                    "location": "Multiple Cities",
                    "mode": "Online",
                    "date": date(2025, 10, 10),
                    "e_eligibility": "Graduate",
                }
            ]

        for exam_data in exams:
            exam, created = Exam.objects.update_or_create(
                name=exam_data["name"], defaults=exam_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Exam created: {exam.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Exam updated: {exam.name}"))

        # -------- Schemes --------
        schemes = [
            {
                "name": "Central Scholarship Scheme",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for meritorious students.",
                "s_eligibility": "12th Pass",
                "benefits": "Covers tuition fees and stipend.",
                "location": "All India",
                "date": date(2025, 4, 5),  # Using start_date as the single date field
            },
            {
                "name": "Startup India Loan",
                "category": "Entrepreneurship",
                "scheme_type": "Loan",
                "description": "Financial support for startups.",
                "s_eligibility": "Graduate",
                "benefits": "Low-interest loan up to 10 Lakhs.",
                "location": "Delhi",
                "date": date(2025, 1, 10),
            },
            {
                "name": "Ayushman Bharat",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Healthcare scheme for low-income families.",
                "s_eligibility": "10th Pass",
                "benefits": "Free health coverage up to 5 Lakhs.",
                "location": "All India",
                "date": date(2025, 3, 15),
            },
            {
                "name": "PM Kisan Samman Nidhi",
                "category": "Employment",
                "scheme_type": "Central Government",
                "description": "Income support for farmers.",
                "s_eligibility": "10th Pass",
                "benefits": "6000 INR per year.",
                "location": "West Bengal",
                "date": date(2025, 2, 5),
            },
            {
                "name": "Skill India Mission",
                "category": "Employment",
                "scheme_type": "Training",
                "description": "Skill development for youth.",
                "s_eligibility": "12th Pass",
                "benefits": "Free training programs.",
                "location": "Maharashtra",
                "date": date(2025, 6, 5),
            },
            {
                "name": "Digital India Initiative",
                "category": "General",
                "scheme_type": "Central Government",
                "description": "Promoting digital infrastructure.",
                "s_eligibility": "Graduate",
                "benefits": "Support for digital adoption.",
                "location": "Karnataka",
                "date": date(2025, 1, 20),
            },
            {
                "name": "National Pension Scheme",
                "category": "Finance",
                "scheme_type": "Central Government",
                "description": "Retirement savings scheme.",
                "s_eligibility": "Graduate",
                "benefits": "Tax benefits and pension.",
                "location": "All India",
                "date": date(2025, 1, 5),
            },
            {
                "name": "State Education Grant",
                "category": "Education",
                "scheme_type": "State Government",
                "description": "Grant for state students.",
                "s_eligibility": "12th Pass",
                "benefits": "Up to 50,000 INR.",
                "location": "Tamil Nadu",
                "date": date(2025, 7, 5),
            },
            {
                "name": "Women Empowerment Loan",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan scheme for women entrepreneurs.",
                "s_eligibility": "Graduate",
                "benefits": "Low-interest loans up to 5 Lakhs.",
                "location": "Hyderabad",
                "date": date(2025, 5, 5),
            },
            {
                "name": "Youth Sports Development",
                "category": "Health",
                "scheme_type": "Welfare",
                "description": "Support for young athletes.",
                "s_eligibility": "12th Pass",
                "benefits": "Scholarships and training support.",
                "location": "Delhi",
                "date": date(2025, 8, 5),
            },
            {
                "name": "PM Awas Yojana",
                "category": "Housing",
                "scheme_type": "Central Government",
                "description": "Housing for all scheme.",
                "s_eligibility": "18+ years, Low Income",
                "benefits": "Subsidy on home loans.",
                "location": "All India",
                "date": date(2025, 1, 15),
            },
            {
                "name": "Ujjwala Yojana",
                "category": "Welfare",
                "scheme_type": "Central Government",
                "description": "Free LPG connection for women.",
                "s_eligibility": "BPL Families",
                "benefits": "Free LPG connection.",
                "location": "All India",
                "date": date(2025, 4, 10),
            },
            {
                "name": "PM Mudra Yojana",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for small businesses.",
                "s_eligibility": "18+ years",
                "benefits": "Loans up to 10 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 8),
            },
            {
                "name": "Stand Up India",
                "category": "Finance",
                "scheme_type": "Loan",
                "description": "Loan for SC/ST and women entrepreneurs.",
                "s_eligibility": "SC/ST/Women",
                "benefits": "Loan from 10 Lakhs to 1 Crore.",
                "location": "All India",
                "date": date(2025, 3, 5),
            },
            {
                "name": "PMEGP",
                "category": "Employment",
                "scheme_type": "Loan",
                "description": "Prime Minister Employment Generation Program.",
                "s_eligibility": "18+ years",
                "benefits": "Subsidy for self-employment.",
                "location": "All India",
                "date": date(2025, 4, 8),
            },
            {
                "name": "NRLM",
                "category": "Employment",
                "scheme_type": "Welfare",
                "description": "National Rural Livelihood Mission.",
                "s_eligibility": "Rural Population",
                "benefits": "Skill development and financial support.",
                "location": "Rural India",
                "date": date(2025, 1, 12),
            },
            {
                "name": "NSAP",
                "category": "Welfare",
                "scheme_type": "Pension",
                "description": "National Social Assistance Programme.",
                "s_eligibility": "Senior Citizens, Widows, Disabled",
                "benefits": "Monthly pension.",
                "location": "All India",
                "date": date(2025, 4, 12),
            },
            {
                "name": "PMJJBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Jeevan Jyoti Bima Yojana.",
                "s_eligibility": "18-50 years",
                "benefits": "Life insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 18),
            },
            {
                "name": "PMSBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Suraksha Bima Yojana.",
                "s_eligibility": "18-70 years",
                "benefits": "Accidental insurance cover of 2 Lakhs.",
                "location": "All India",
                "date": date(2025, 1, 22),
            },
            {
                "name": "APY",
                "category": "Pension",
                "scheme_type": "Central Government",
                "description": "Atal Pension Yojana.",
                "s_eligibility": "18-40 years",
                "benefits": "Fixed pension after 60 years.",
                "location": "All India",
                "date": date(2025, 1, 25),
            },
            {
                "name": "PMFBY",
                "category": "Insurance",
                "scheme_type": "Central Government",
                "description": "Pradhan Mantri Fasal Bima Yojana.",
                "s_eligibility": "Farmers",
                "benefits": "Crop insurance.",
                "location": "All India",
                "date": date(2025, 4, 15),
            },
            {
                "name": "State Health Scheme",
                "category": "Health",
                "scheme_type": "State Government",
                "description": "Health insurance for state residents.",
                "s_eligibility": "State Residents",
                "benefits": "Health coverage up to 5 Lakhs.",
                "location": "Kerala",
                "date": date(2025, 6, 8),
            },
            {
                "name": "Student Credit Card",
                "category": "Education",
                "scheme_type": "Loan",
                "description": "Education loan for students.",
                "s_eligibility": "12th Pass",
                "benefits": "Loan up to 10 Lakhs for education.",
                "location": "West Bengal",
                "date": date(2025, 5, 8),
            },
            {
                "name": "Kanyashree Prakalpa",
                "category": "Education",
                "scheme_type": "Scholarship",
                "description": "Scholarship for girl students.",
                "s_eligibility": "Girl Students",
                "benefits": "Annual scholarship.",
                "location": "West Bengal",
                "date": date(2025, 4, 8),
            },
            {
                "name": "Rupashree Prakalpa",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial assistance for marriage of girls.",
                "s_eligibility": "Girls from BPL families",
                "benefits": "One-time financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 12),
            },
            {
                "name": "Yuvashree Arpan",
                "category": "Employment",
                "scheme_type": "Allowance",
                "description": "Unemployment allowance for youth.",
                "s_eligibility": "Graduate, Unemployed",
                "benefits": "Monthly allowance.",
                "location": "West Bengal",
                "date": date(2025, 5, 12),
            },
            {
                "name": "Krishak Bandhu",
                "category": "Welfare",
                "scheme_type": "Financial Assistance",
                "description": "Financial support for farmers.",
                "s_eligibility": "Farmers",
                "benefits": "Annual financial assistance.",
                "location": "West Bengal",
                "date": date(2025, 4, 15),
            },
            {
                "name": "Swasthya Sathi",
                "category": "Health",
                "scheme_type": "Insurance",
                "description": "Health insurance for families.",
                "s_eligibility": "All Residents",
                "benefits": "Health coverage up to 5 Lakhs per family.",
                "location": "West Bengal",
                "date": date(2025, 1, 12),
            },
            {
                "name": "Mukhyamantri Tirth Yatra Yojana",
                "category": "Welfare",
                "scheme_type": "State Government",
                "description": "Free pilgrimage for senior citizens.",
                "s_eligibility": "Senior Citizens",
                "benefits": "Free travel to religious places.",
                "location": "Delhi",
                "date": date(2025, 4, 18),
            },
            {
                "name": "Delhi Startup Policy",
                "category": "Entrepreneurship",
                "scheme_type": "Subsidy",
                "description": "Support for startups in Delhi.",
                "s_eligibility": "Startups registered in Delhi",
                "benefits": "Financial support and subsidies.",
                "location": "Delhi",
                "date": date(2025, 6, 12),
            },
            {
                "name": "National Green Corps",
                "category": "Environment",
                "scheme_type": "Conservation",
                "description": "Engaging youth in environmental conservation activities.",
                "s_eligibility": "Schools and Colleges",
                "benefits": "Funding for eco-clubs and environmental projects.",
                "location": "All India",
                "date": date(2025, 3, 20),
            },
            {
                "name": "Green India Mission",
                "category": "Environment",
                "scheme_type": "Afforestation",
                "description": "Increasing forest cover and improving ecosystem services.",
                "s_eligibility": "Forest Departments, NGOs",
                "benefits": "Financial assistance for afforestation projects.",
                "location": "All India",
                "date": date(2025, 4, 22),
            },
            {
                "name": "National Solar Mission",
                "category": "Environment",
                "scheme_type": "Renewable Energy",
                "description": "Promoting solar energy adoption across India.",
                "s_eligibility": "Households, Institutions, Industries",
                "benefits": "Subsidies for solar panel installation.",
                "location": "All India",
                "date": date(2025, 5, 15),
            },
            {
                "name": "Swachh Bharat Fellowship",
                "category": "Environment",
                "scheme_type": "Scholarship",
                "description": "Fellowship for youth working on sanitation projects.",
                "s_eligibility": "Graduate, Post Graduate",
                "benefits": "Monthly stipend and project funding.",
                "location": "All India",
                "date": date(2025, 6, 10),
            },
            {
                "name": "Eco-warrior Scholarship",
                "category": "Environment",
                "scheme_type": "Scholarship",
                "description": "Scholarship for students pursuing environmental studies.",
                "s_eligibility": "12th Pass with Science background",
                "benefits": "Tuition fee waiver and research grant.",
                "location": "All India",
                "date": date(2025, 7, 5),
            },
            {
                "name": "National Merit Scholarship",
                "category": "Scholarships",
                "scheme_type": "Merit-based",
                "description": "Scholarship for academically brilliant students from low-income families.",
                "s_eligibility": "Class 12 passed with 90%+ marks",
                "benefits": "Full tuition coverage and monthly stipend.",
                "location": "All India",
                "date": date(2025, 8, 1),
            },
            {
                "name": "Prime Minister's Research Fellowship",
                "category": "Scholarships",
                "scheme_type": "Research",
                "description": "Fellowship for students pursuing PhD in STEM fields.",
                "s_eligibility": "MTech/MSc with 8.0 CGPA",
                "benefits": "Monthly stipend of 70,000 INR for 5 years.",
                "location": "All India",
                "date": date(2025, 9, 15),
            },
            {
                "name": "Sports Talent Search Scholarship",
                "category": "Scholarships",
                "scheme_type": "Sports",
                "description": "Scholarship for young athletes with exceptional talent.",
                "s_eligibility": "Age 14-25 years with sports achievements",
                "benefits": "Training support and financial assistance.",
                "location": "All India",
                "date": date(2025, 10, 5),
            },
            {
                "name": "Cultural Talent Search Scholarship",
                "category": "Scholarships",
                "scheme_type": "Arts",
                "description": "Scholarship for students excelling in performing arts.",
                "s_eligibility": "Age 10-25 years with cultural achievements",
                "benefits": "Training support and performance opportunities.",
                "location": "All India",
                "date": date(2025, 11, 20),
            },
            {
                "name": "Single Girl Child Scholarship",
                "category": "Scholarships",
                "scheme_type": "Gender-based",
                "description": "Scholarship for single girl children pursuing higher education.",
                "s_eligibility": "Single girl child, family income < 6 LPA",
                "benefits": "Full tuition fee waiver and hostel charges.",
                "location": "All India",
                "date": date(2025, 12, 10),
            },
            {
                "name": "SC/ST Post-Matric Scholarship",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Scholarship for SC/ST students pursuing post-matric education.",
                "s_eligibility": "SC/ST students with family income < 2.5 LPA",
                "benefits": "Maintenance allowance and tuition fees.",
                "location": "All India",
                "date": date(2025, 1, 30),
            },
            {
                "name": "OBC Scholarship Scheme",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Financial assistance for OBC students pursuing higher education.",
                "s_eligibility": "OBC students with family income < 1 LPA",
                "benefits": "Maintenance allowance and tuition fees.",
                "location": "All India",
                "date": date(2025, 2, 25),
            },
            {
                "name": "Minority Scholarship",
                "category": "Scholarships",
                "scheme_type": "Social Welfare",
                "description": "Scholarship for students from minority communities.",
                "s_eligibility": "Minority community students, family income < 2 LPA",
                "benefits": "Tuition fees and maintenance allowance.",
                "location": "All India",
                "date": date(2025, 3, 15),
            },
            {
                "name": "Differently-abled Student Scholarship",
                "category": "Scholarships",
                "scheme_type": "Inclusive Education",
                "description": "Scholarship for students with disabilities pursuing education.",
                "s_eligibility": "40% or more disability, pursuing education",
                "benefits": "Tuition fees, books, and assistive devices.",
                "location": "All India",
                "date": date(2025, 4, 20),
            },
            {
                "name": "Waste Management Innovation Grant",
                "category": "Environment",
                "scheme_type": "Innovation",
                "description": "Grant for innovative waste management solutions.",
                "s_eligibility": "Startups, NGOs, Researchers",
                "benefits": "Funding up to 50 Lakhs for project implementation.",
                "location": "All India",
                "date": date(2025, 5, 25),
            },
            {
                "name": "Water Conservation Fellowship",
                "category": "Environment",
                "scheme_type": "Research",
                "description": "Fellowship for research on water conservation techniques.",
                "s_eligibility": "MTech/PhD in Environmental Science",
                "benefits": "Monthly stipend and research grant.",
                "location": "All India",
                "date": date(2025, 6, 15),
            },
            {
                "name": "Climate Change Research Grant",
                "category": "Environment",
                "scheme_type": "Research",
                "description": "Grant for research projects on climate change mitigation.",
                "s_eligibility": "Research Institutions, Universities",
                "benefits": "Funding up to 1 Crore for research projects.",
                "location": "All India",
                "date": date(2025, 7, 20),
            },
            {
                "name": "Organic Farming Subsidy",
                "category": "Environment",
                "scheme_type": "Agriculture",
                "description": "Subsidy for farmers adopting organic farming practices.",
                "s_eligibility": "Farmers with minimum 1 acre land",
                "benefits": "50% subsidy on organic inputs and certification.",
                "location": "All India",
                "date": date(2025, 8, 10),
            },
            {
                "name": "Electric Vehicle Adoption Incentive",
                "category": "Environment",
                "scheme_type": "Transport",
                "description": "Financial incentive for purchasing electric vehicles.",
                "s_eligibility": "Individual buyers, Fleet operators",
                "benefits": "Up to 1.5 Lakh subsidy on electric vehicles.",
                "location": "All India",
                "date": date(2025, 9, 5),
            },
            {
                "name": "Renewable Energy Startup Fund",
                "category": "Environment",
                "scheme_type": "Entrepreneurship",
                "description": "Funding for startups working in renewable energy sector.",
                "s_eligibility": "Registered startups in renewable energy",
                "benefits": "Seed funding up to 2 Crores and mentorship.",
                "location": "All India",
                "date": date(2025, 10, 15),
            }
        ]

        for scheme_data in schemes:
            scheme, created = Scheme.objects.update_or_create(
                name=scheme_data["name"], defaults=scheme_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Scheme created: {scheme.name}"))
            else:
                self.stdout.write(self.style.SUCCESS(f"🔄 Scheme updated: {scheme.name}"))